// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMotors.Core.Data;

namespace WebMotors.WebMotorsWeb.Migrations
{
    [DbContext(typeof(WebMotorsDatabaseContext))]
    partial class WebMotorsDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebMotors.Core.Entities.Anuncio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(45)")
                        .HasMaxLength(45);

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(45)")
                        .HasMaxLength(45);

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quilometragem")
                        .HasColumnType("int");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .HasColumnType("nvarchar(45)")
                        .HasMaxLength(45);

                    b.HasKey("Id");

                    b.ToTable("tb_AnuncioWebmotors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = 2020,
                            Marca = "Tesla",
                            Modelo = "Cybertruck",
                            Observacao = "Tesla Cybertruck 2020 v1.0",
                            Quilometragem = 0,
                            Versao = "1.0"
                        },
                        new
                        {
                            Id = 2,
                            Ano = 2019,
                            Marca = "Tesla",
                            Modelo = "Roaster",
                            Observacao = "Tesla Roaster 2019 v1.0",
                            Quilometragem = 0,
                            Versao = "1.0"
                        },
                        new
                        {
                            Id = 3,
                            Ano = 2020,
                            Marca = "Fiat",
                            Modelo = "Argo",
                            Observacao = "Fiat Argo",
                            Quilometragem = 0,
                            Versao = "1.0"
                        },
                        new
                        {
                            Id = 4,
                            Ano = 2020,
                            Marca = "Ferrari",
                            Modelo = "Spider",
                            Observacao = "Ferrari Spider v1.0 2020",
                            Quilometragem = 0,
                            Versao = "1.0"
                        },
                        new
                        {
                            Id = 5,
                            Ano = 2018,
                            Marca = "Rolls-Royce",
                            Modelo = "Phanton",
                            Observacao = "Rolls-Royce Phanton VIII 2018",
                            Quilometragem = 0,
                            Versao = "III"
                        },
                        new
                        {
                            Id = 6,
                            Ano = 2018,
                            Marca = "Lamborghini",
                            Modelo = "Aventador",
                            Observacao = "Lamborghini aVentador 2020",
                            Quilometragem = 0,
                            Versao = "1.0"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
